### ISSUE TITLE
A few typos in Specification v0.1?

### ISSUE THREAD

**Issue by LaurentAjdnik** [qir-alliance/qir-spec#5]
If I'm not mistaken (not being a native speaker), there might be a few typos in Specification v0.1:

| File | Section | Current version | Proposed version |
| --- | --- | --- | --- |
| 1_Data_Types.md | Qubits | so that it **cen** be distinguished | so that it **can** be distinguished |
| 2_Callables.md | (Intro) | We use **to** term callable to mean | We use **the** term callable to mean |
| 2_Callables.md | Wrapper functions | which used for closures | which **is** used for closures |
| 2_Callables.md | Applying Functors to Callable Values | by **adding** replacing | by replacing |
| 2_Callables.md | Memory Management Table | the table is defined as global constant | the table is defined as **a** global constant |
| 5_Metadata.md | Representing Source-Language Attributes | For instance, in Q# attributes are compile-time constant values | For instance in Q#**,** attributes are compile-time constant values |
| 7_Profiles.md | (Both profiles)| **TBD** | **To be determined** (written in full, for those who might not know the acronym?) |

More generally, could it be considered good practice to replace occurrences of can't/don't/doesn't by cannot/do not/does not (which are more formal)?

If any of these are confirmed, I'll be happy to PR corrections, as soon as the CLA becomes available.

**Comment by bettinaheim** [comment]
@LaurentAjdnik Thank you for filing this! 
I believe there is also a typo in at least one of the signatures. We'll push an update.
